name: CD Release Pipeline

on:
  push:
    tags:
      - 'v*.*.*' # Triggers only when a tag matching v1.0.0 is pushed

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify Compilation before Release
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      
      - name: Run Build Check
        run: |
          go mod tidy
          go build ./...

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
